Install Numpy-stl library


In [1]:
import cv2
import os
from PIL import Image
import matplotlib.pyplot as plt
import glob
import numpy as np
from stl import mesh

Simple example on how to create a cube using triangles for faces

In [ ]:
import cv2
im = Image.open("7.png").convert('RGBA')
im=np.array(im)
mi = Image.open("6.png").convert('RGBA')
mi=np.array(mi)

# cv2.imwrite("h.png",img)

im[np.where(np.all(im != (255,255,255,255) , axis=2))]=[0,0,0,0]
l,m=np.where(np.all(im == [0,0,0,0], axis=2))
mi[l,m]=im[l,m]
cv2.imwrite("hh.png",mi)

In [ ]:
im = Image.open("hh.png").convert('RGBA')
im=np.array(im)
im[np.where(np.all(im == (255,255,255,255) , axis=2))]=[0,0,0,0]
cv2.imwrite("hhh.png",im)

In [3]:
import cv2
img=cv2.imread("11.png")
# cv2.imwrite("h.png",img)


l,m=np.where(np.all(img > [5,5,5], axis=2))

# print(min(l),max(m))

In [6]:
grey_img = Image.open('11.jpg').convert('L')

max_size=(720,720)
max_height=10
min_height=0
print("ggg",min(l))
#height=0 for minPix
#height=maxHeight for maxPIx

grey_img.thumbnail(max_size)
imageNp = np.array(grey_img)
maxPix=imageNp.max()
minPix=imageNp.min()


print(imageNp)
(ncols,nrows)=grey_img.size
# print(ncols,nrows)
(ncols,nrows)=grey_img.size
vertices=np.zeros((nrows,ncols,3))
vertices1=np.zeros((nrows,ncols,3))

b=0.8
for x in range(0, ncols):
    for y in range(0, nrows):
        pixelIntensity = imageNp[y][x]
        z = (pixelIntensity * max_height) / maxPix
    # b=z
    # print("ibtehaj",z)
    # if (z!=0):
    #   b=z
    # else:
    #   z=b
    # # print("ali",z) if (z!=0):
    #   b=z
    #print(imageNp[y][x])
    # z=1
    # b=0
        vertices[y][x]=(x, y, z)
    # vertices1[y][x]=(x, y, -z)


faces=[]

for x in range(min(m),max(m)-5):
    s=np.where(m==x)
    s=s[0]
  # print(s)
    for h in set(s):
        y=l[h]
    # print(x,y)
    # create face 1
        if(y<=max(l)-5):
            vertice1 = vertices[y][x]
              # print(y)
            vertice2 = vertices[y][x+1]
            vertice3 = vertices[y+1][x+1]
              # vertice4 = vertices[y][x+1]
            face1 = np.array([vertice1,vertice2,vertice3])

            # create face 2 
            vertice1 = vertices[y][x]
            vertice2 = vertices[y+1][x]
            vertice3 = vertices[y+1][x+1]
                  # vertice4 = vertices[y+1][x]
            face2 = np.array([vertice1,vertice2,vertice3])
              #create  face 3
              #create  face 3

    #   vertice1 = vertices1[y][x]
    #   vertice2 = vertices1[y+1][x]
    #   vertice3 = vertices1[y+1][x+1]
    #   # vertice4 = vertices[y][x+1]
    #   face3 = np.array([vertice1,vertice2,vertice3])

    # # c2reate face 4 
    #   vertice1 = vertices1[y][x]
    #   vertice2 = vertices1[y][x+1]3
    #   vertice3 = vertices1[y+1][x+1]
    #   # vertice4 = vertices[y+1][x]
    #   face4 = np.array([vertice1,vertice2,vertice3])
        faces.append(face1)
        faces.append(face2)
      # faces.append(face3)
      # faces.append(face4)
    # except:
    #    pass

print(f"number of faces: {len(faces)}")
facesNp = np.array(faces)
# Create the mesh
print(facesNp.shape[0])
surface = mesh.Mesh(np.zeros(facesNp.shape[0] , dtype=mesh.Mesh.dtype))
for i, f in enumerate(faces):
    for j in range(3):
          surface.vectors[i][j] = facesNp[i][j]
# import meshio
# points,cell=meshzoo.cube_hexa(surface,0,11)
# meshio.write("cube.e", points, {"tetra": cells})
# Write the mesh to file "cube.stl"
surface.save('texture_11.stl')
print(surface)

ggg 8
[[238 238 238 ... 238 238 238]
 [238 238 238 ... 238 238 238]
 [238 238 238 ... 238 238 238]
 ...
 [238 238 238 ... 238 238 238]
 [238 238 238 ... 238 238 238]
 [238 238 238 ... 238 238 238]]
number of faces: 16372
16372


In [7]:
grey_img = Image.open('11.jpg').convert('L')

max_size=(720,720)
max_height=10
min_height=0
print("ggg",min(l))
#height=0 for minPix
#height=maxHeight for maxPIx

grey_img.thumbnail(max_size)
imageNp = np.array(grey_img)
maxPix=imageNp.max()
minPix=imageNp.min()


print(imageNp)
(ncols,nrows)=grey_img.size
# print(ncols,nrows)
(ncols,nrows)=grey_img.size
vertices=np.zeros((nrows,ncols,3))
vertices1=np.zeros((nrows,ncols,3))

b=0.8
for x in range(min(m), ncols):
    for y in range(min(l), nrows):
        pixelIntensity = imageNp[y][x]
        z = (pixelIntensity * max_height) / maxPix
    # b=z
    # print("ibtehaj",z)
    # if (z!=0):
    #   b=z
    # else:
    #   z=b
    # # print("ali",z) if (z!=0):
    #   b=z
    #print(imageNp[y][x])
    # z=1
    # b=0
        vertices[y][x]=(x, y, z)
    # vertices1[y][x]=(x, y, -z)


faces=[]

for x in range(min(m),max(m)-5):
    s=np.where(m==x)
    s=s[0]
  # print(s)
    for h in set(s):
        y=l[h]
    # print(x,y)
    # create face 1
        if(y<=max(l)-5):
            vertice1 = vertices[y][x]
              # print(y)
            vertice2 = vertices[y][x+1]
            vertice3 = vertices[y+1][x+1]
              # vertice4 = vertices[y][x+1]
            face1 = np.array([vertice1,vertice2,vertice3])

            # create face 2 
            vertice1 = vertices[y][x]
            vertice2 = vertices[y+1][x]
            vertice3 = vertices[y+1][x+1]
                  # vertice4 = vertices[y+1][x]
            face2 = np.array([vertice1,vertice2,vertice3])
              #create  face 3
              #create  face 3

    #   vertice1 = vertices1[y][x]
    #   vertice2 = vertices1[y+1][x]
    #   vertice3 = vertices1[y+1][x+1]
    #   # vertice4 = vertices[y][x+1]
    #   face3 = np.array([vertice1,vertice2,vertice3])

    # # c2reate face 4 
    #   vertice1 = vertices1[y][x]
    #   vertice2 = vertices1[y][x+1]3
    #   vertice3 = vertices1[y+1][x+1]
    #   # vertice4 = vertices[y+1][x]
    #   face4 = np.array([vertice1,vertice2,vertice3])
        faces.append(face1)
        faces.append(face2)
      # faces.append(face3)
      # faces.append(face4)
    # except:
    #    pass

print(f"number of faces: {len(faces)}")
facesNp = np.array(faces)
# Create the mesh
print(facesNp.shape[0])
surface = mesh.Mesh(np.zeros(facesNp.shape[0] , dtype=mesh.Mesh.dtype))
for i, f in enumerate(faces):
    for j in range(3):
          surface.vectors[i][j] = facesNp[i][j]
# import meshio
# points,cell=meshzoo.cube_hexa(surface,0,11)
# meshio.write("cube.e", points, {"tetra": cells})
# Write the mesh to file "cube.stl"
surface.save('texture_11_1.stl')
print(surface)

ggg 8
[[238 238 238 ... 238 238 238]
 [238 238 238 ... 238 238 238]
 [238 238 238 ... 238 238 238]
 ...
 [238 238 238 ... 238 238 238]
 [238 238 238 ... 238 238 238]
 [238 238 238 ... 238 238 238]]
number of faces: 16372
16372


opneimport cv2imiiiiiiCreate surface 1000 x 5000 with N triangles

In [ ]:

grey_img = Image.open('2.png').convert('L')

max_size=(720,720)
max_height=10 
min_height=0
print("ggg",min(l))
#height=0 for minPix
#height=maxHeight for maxPIx

grey_img.thumbnail(max_size)
imageNp = np.array(grey_img)
maxPix=imageNp.max()
minPix=imageNp.min()


print(imageNp)
(ncols,nrows)=grey_img.size
# print(ncols,nrows)
(ncols,nrows)=grey_img.size
vertices=np.zeros((nrows,ncols,3))
vertices1=np.zeros((nrows,ncols,3))

for x in range(min(m), ncols):
  for y in range(min(l), nrows):
    pixelIntensity = imageNp[y][x]
    z = (pixelIntensity * max_height) / maxPix
    # b=z
    # print("ibtehaj",z)
    # if (z!=0):
    #   b=z
    # else:
    #   z=b
    # print("ali",z)
    #print(imageNp[y][x])
    # z=-1
    b=0
    vertices[y][x]=(x, y, 5)
    vertices1[y][x]=(x, y, -5)


faces=[]

for x in range(min(m),max(m)-5):
  s=np.where(m==x)
  s=s[0]
  # print(s)
  for h in set(s):
    y=l[h]
    # print(y)
    # create face 1
    if(y<=max(l)-5):
      vertice1 = vertices[y][x]
      vertice2 = vertices1[y][x]
      # vertice3 = vertices1[y+1][x]
      vertice3 = vertices1[y+1][x+1]
      # vertice4 = vertices[y][x+1]
      face1 = np.array([vertice1,vertice2,vertice3])

    # create face 2 
      vertice1 = vertices[y][x]
      vertice2 = vertices[y][x+1]
      vertice3 = vertices1[y+1][x+1]
      # vertice4 = vertices[y+1][x]
      face2 = np.array([vertice1,vertice2,vertice3])
      #create  face 3

    #   vertice1 = vertices1[y][x]
    #   vertice2 = vertices1[y+1][x]
    #   vertice3 = vertices1[y+1][x+1]
    #   # vertice4 = vertices[y][x+1]
    #   face3 = np.array([vertice1,vertice2,vertice3])

    # # create face 4 
    #   vertice1 = vertices1[y][x]
    #   vertice2 = vertices1[y][x+1]
    #   vertice3 = vertices1[y+1][x+1]
    #   # vertice4 = vertices[y+1][x]
    #   face4 = np.array([vertice1,vertice2,vertice3])
      faces.append(face1)
      # faces.append(face4)
      # faces.append(face3)
      faces.append(face2)
    # except:
    #    pass

print(f"number of faces: {len(faces)}")
facesNp = np.array(faces)
# Create the mesh
print(facesNp.shape[0])
surface = mesh.Mesh(np.zeros(facesNp.shape[0] , dtype=mesh.Mesh.dtype))
for i, f in enumerate(faces):
    for j in range(3):
          surface.vectors[i][j] = facesNp[i][j]
   
# Write the mesh to file "cube.stl"
surface.save('Depth_add.stl')
print(surface)

In [ ]:

grey_img = Image.open('2.png').convert('L')

max_size=(720,720)
max_height=10 
min_height=0
print("ggg",min(l))
#height=0 for minPix
#height=maxHeight for maxPIx

grey_img.thumbnail(max_size)
imageNp = np.array(grey_img)
maxPix=imageNp.max()
minPix=imageNp.min()


print(imageNp)
(ncols,nrows)=grey_img.size
# print(ncols,nrows)
(ncols,nrows)=grey_img.size
vertices=np.zeros((nrows,ncols,3))
vertices1=np.zeros((nrows,ncols,3))

for x in range(min(m), ncols):
  for y in range(min(l), nrows):
    pixelIntensity = imageNp[y][x]
    z = (pixelIntensity * max_height) / maxPix
    # b=z
    # print("ibtehaj",z)
    # if (z!=0):
    #   b=z
    # else:
    #   z=b
    # print("ali",z)
    #print(imageNp[y][x])
    # z=-1
    b=0
    vertices[y][x]=(x, y, 5)
    vertices1[y][x]=(x, y, -5)


faces=[]

for x in range(min(m),max(m)-5):
  s=np.where(m==x)
  s=s[0]
  # print(s)
  for h in set(s):
    y=l[h]
    # print(y)
    # create face 1
    if(y<=max(l)-5):
      vertice1 = vertices[y][x]
      vertice2 = vertices1[y][x]
      # vertice3 = vertices1[y+1][x]
      vertice3 = vertices1[y+1][x+1]
      # vertice4 = vertices[y][x+1]
      face1 = np.array([vertice1,vertice2,vertice3])

    # create face 2 
      vertice1 = vertices[y][x]
      vertice2 = vertices[y][x+1]
      vertice3 = vertices1[y+1][x+1]
      # vertice4 = vertices[y+1][x]
      face2 = np.array([vertice1,vertice2,vertice3])
      #create  face 3

      vertice1 = vertices1[y][x]
      vertice2 = vertices[y+1][x]
      vertice3 = vertices[y+1][x+1]
      # vertice4 = vertices[y][x+1]
      face3 = np.array([vertice1,vertice2,vertice3])

    # # create face 4 
      vertice1 = vertices1[y][x]
      vertice2 = vertices1[y][x+1]
      vertice3 = vertices[y+1][x+1]
      # vertice4 = vertices[y+1][x]
      face4 = np.array([vertice1,vertice2,vertice3])
      faces.append(face1)
      faces.append(face2)
      faces.append(face3)
      faces.append(face4)
    # except:
    #    pass

print(f"number of faces: {len(faces)}")
facesNp = np.array(faces)
# Create the mesh
print(facesNp.shape[0])
surface = mesh.Mesh(np.zeros(facesNp.shape[0] , dtype=mesh.Mesh.dtype))
for i, f in enumerate(faces):
    for j in range(3):
          surface.vectors[i][j] = facesNp[i][j]
   
# Write the mesh to file "cube.stl"
surface.save('Depth_add_1.stl')
print(surface)

In [ ]:
import cv2
from PIL import Image
import cv2
from PIL import Image
import matplotlib.pyplot as plt
import glob
import numpy as np
import matplotlib.pyplot as plt
img = Image.open("input/25.jpg")
img=np.array(img)
# cv2.imwrite("h.png",img)
# img[np.where(np.all(img == [255,255,255,255], axis=2))]==[0,0,0,0]
l,m=np.where(np.all(img != [255,255,255], axis=-1))
grey_img = Image.open("input/25.jpg").convert('L')

max_size=(720,720)
max_height=0
min_height=0
print("ggg",max(l))
# import meshio
# points,cell=meshzoo.cube_hexa(surface,0,11)
# meshio.write("cube.e", points, {"tetra": cells})
#height=0 for minPix
#height=maxHeight for maxPIx

grey_img.thumbnail(max_size)
imageNp = np.array(grey_img)
maxPix=imageNp.max()
minPix=imageNp.min()


print(imageNp)
# print(ncols,nrows)
(ncols,nrows)=grey_img.size
vertices=np.zeros((nrows,ncols,3))
vertices1=np.zeros((nrows,ncols,3))

for x in range(min(m), ncols):
  for y in range(min(l), nrows):
    # pixelIntensity = imageNp[y][x]
    # z = (pixelIntensity * max_height) / maxPix
    # b=z
    # print("ibtehaj",z)
    # if (z!=0):
    #   b=z
    # else:
    #   z=b
    # print("ali",z)
    #print(imageNp[y][x])
    z=0
    # b=0
    vertices[y][x]=(x, y, z)
    vertices1[y][x]=(x, y, -z)


faces=[]

for x in range(min(m),max(m)-5):
  s=np.where(m==x)
  s=s[0]
  print(x)
  for h in set(s):
    y=l[h]
    #print(x)
    # create face 1
    if(y<=max(l)-5):
      vertice1 = vertices[y][x]
      # print(y)
      vertice2 = vertices[y][x+1]
      vertice3 = vertices[y+1][x+1]
      # vertice4 = vertices[y][x+1]
      face1 = np.array([vertice1,vertice2,vertice3])
      print()
    # create face 2 
      vertice1 = vertices[y][x]
      vertice2 = vertices[y+1][x]
      vertice3 = vertices[y+1][x+1]
      # vertice4 = vertices[y+1][x]
      face2 = np.array([vertice1,vertice2,vertice3])
      #create  face 3

    #   vertice1 = vertices1[y][x]
    #   vertice2 = vertices1[y+1][x]
    #   vertice3 = vertices1[y+1][x+1]
    #   # vertice4 = vertices[y][x+1]
    #   face3 = np.array([vertice1,vertice2,vertice3])

    # # create face 4 
    #   vertice1 = vertices1[y][x]
    #   vertice2 = vertices1[y][x+1]
    #   vertice3 = vertices1[y+1][x+1]
    #   # vertice4 = vertices[y+1][x]
    #   face4 = np.array([vertice1,vertice2,vertice3])
      faces.append(face1)
      faces.append(face2)
      # faces.append(face3)
      # faces.append(face4)
    # except:
    #    pass

print(f"number of faces: {len(faces)}")
facesNp = np.array(faces)
# Create the mesh
print(facesNp.shape[0])
surface = mesh.Mesh(np.zeros(facesNp.shape[0] , dtype=mesh.Mesh.dtype))
for i, f in enumerate(faces):
    for j in range(3):
          surface.vectors[i][j] = facesNp[i][j]
   
# Write the mesh to file "cube.stl"
surface.save('output/25.stl')
print(surface)

In [ ]:
import cv2
import os
from PIL import Image
import matplotlib.pyplot as plt
import glob
import numpy as np
from stl import mesh
for image in glob.glob("/home/mitho/Documents/ibtehaj_1/fasion/mesh/mask/*.png"):
    img=cv2.imread(image)
    # cv2.imwrite("h.png",img)
    # np.where(np.all(img  [0,0,0], axis=2))=[255,255,255]
    l,m=np.where(np.all(img > [5,5,5], axis=2))
    image=os.path.basename(image)
    image=os.path.splitext(image)[0]
    imag="/home/mitho/Documents/ibtehaj_1/fasion/mesh/input/"+image+".jpg"
    grey_img = Image.open(imag).convert('L')
    (ncols,nrows)=grey_img.size
    max_size=(ncols,nrows)
    max_height=10
    min_height=0
    print("ggg",min(m),max(m))
    # import meshio
    # points,cell=meshzoo.cube_hexa(surface,0,11)
    # meshio.write("cube.e", points, {"tetra": cells})
    #height=0 for minPix
    #height=maxHeight for maxPIx

    grey_img.thumbnail(max_size)
    imageNp = np.array(grey_img)
    maxPix=imageNp.max()
    minPix=imageNp.min()


    print(imageNp)
    # print(ncols,nrows)
    (ncols,nrows)=grey_img.size
    vertices=np.zeros((nrows,ncols,3))
    # vertices1=np.zeros((nrows,ncols,3))

    for x in range(min(m), ncols):
        for y in range(min(l), nrows):
        # pixelIntensity = imageNp[y][x]
        # z = (pixelIntensity * max_height) / maxPix
        # b=z
        # print("ibtehaj",z)
        # if (z!=0):
        #   b=z
        # else:
        #   z=b
        # print("ali",z)
        #print(imageNp[y][x])
            z=0
        # b=0
            vertices[y][x]=(x, y, z)
        # vertices1[y][x]=(x, y, -z)


    faces=[]

    for x in range(min(m),max(m)-5):
        s=np.where(m==x)
        s=s[0]
        print(x)
        for h in set(s):
            y=l[h]
        
        # create face 1
            if(y<=max(l)-5):
                vertice1 = vertices[y][x]
              # print(y)
                vertice2 = vertices[y][x+1]
                vertice3 = vertices[y+1][x+1]
              # vertice4 = vertices[y][x+1]
                face1 = np.array([vertice1,vertice2,vertice3])

            # create face 2 
                vertice1 = vertices[y][x]
                vertice2 = vertices[y+1][x]
                vertice3 = vertices[y+1][x+1]
                  # vertice4 = vertices[y+1][x]
                face2 = np.array([vertice1,vertice2,vertice3])
                  #create  face 3

                faces.append(face1)
                faces.append(face2)


    print(f"number of faces: {len(faces)}")
    facesNp = np.array(faces)
    # Create the mesh
    print(facesNp.shape[0])
    surface = mesh.Mesh(np.zeros(facesNp.shape[0] , dtype=mesh.Mesh.dtype))
    for i, f in enumerate(faces):
        for j in range(3):
              surface.vectors[i][j] = facesNp[i][j]
    name=os.path.basename(image)
    name=os.path.splitext(name)[0]
    # Write the mesh to file "cube.stl"
    surface.save("/home/mitho/Documents/ibtehaj_1/fasion/mesh/output/"+ name+".stl")
    print(surface)

ggg 417 897
[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
417
418
419
420
421
422
423
424
425
426
427
428
429
430
431
432
433
434
435
436
437
438
439
440
441
442
443
444
445
446
447
448
449
450
451
452
453
454
455
456
457
458
459
460
461
462
463
464
465
466
467
468
469
470
471
472
473
474
475
476
477
478
479
480
481
482
483
484
485
486
487
488
489
490
491
492
493
494
495
496
497
498
499
500
501
502
503
504
505
506
507
508
509
510
511
512
513
514
515
516
517
518
519
520
521
522
523
524
525
526
527
528
529
530
531
532
533
534
535
536
537
538
539
540
541
542
543
544
545
